name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step1
        run: pip install flake8
      - name: step2
        run: python3 -m flake8 ./ --ignore=F401,E402
  python_test:
    runs-on: ubuntu-latest
    needs: code_style
    steps:
      - uses: actions/checkout@v2
      - name: step1
        run: |
          pip install -e '.[test]'
          python3 -m coverage run -m pytest
          python3 -m coverage report
          
  bulding:
    runs-on: ubuntu-latest
    needs: python_test
    steps:
      - uses: actions/checkout@v2
      
      - name: step1
        run: docker build -t maxmimfafa/calculator .
      - name: step2
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: step3
        run:  | 
          docker login 
          docker push maxmimfafa/calculator 
